

Vagrant.configure("2") do |config|

  WIN_IP = "192.168.56.10"
  KALI_IP = "192.168.56.11"

  config.vm.define "windows-target" do |windows|
    windows.vm.box = "gusztavvargadr/windows-10"
    windows.vm.hostname = "win-target"
  
    windows.vm.network "private_network", ip: WIN_IP, virtualbox__intnet: "sandbox_net"

    windows.vm.synced_folder "files/", "C:\\vagrant", create: true

    # Disable Windows defender
    windows.vm.provision "shell", inline: <<-SHELL
      Set-ItemProperty -Path "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender" -Name "DisableAntiSpyware" -Value 1 -Type DWord -Force
      Set-MpPreference -DisableRealtimeMonitoring $true -ErrorAction SilentlyContinue
      Set-MpPreference -SubmitSamplesConsent NeverSend -ErrorAction SilentlyContinue
      Set-NetFirewallProfile -Profile Domain, Public, Private -Enabled False
    SHELL
  
  end

  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali"
    kali.vm.box_version = "2024.4.0"

    kali.vm.network "private_network", ip: KALI_IP, virtualbox__intnet: "sandbox_net"


    kali.vm.provider "virtualbox" do |vb|
      # Set a short, simple name for the VM

      vb.memory = "4096"
      vb.cpus = "8"

      vb.name = "Kali"
    end

    # Shell provisioner to install packages
    kali.vm.provision "shell", path: "kali_install.sh"
  end


end
