

Vagrant.configure("2") do |config|

  WIN_IP = "192.168.56.10"
  KALI_IP = "192.168.56.11"

  config.vm.define "windows-target" do |windows|
    windows.vm.box = "StefanScherer/windows_10"
    windows.vm.hostname = "win-target"
  
    windows.vm.network "private_network", ip: WIN_IP, virtualbox__intnet: "sandbox_net"

    windows.vm.synced_folder "files/", "C:\\vagrant", create: true
  
  end

  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali"
    kali.vm.box_version = "2024.4.0"

    kali.vm.network "private_network", ip: KALI_IP, virtualbox__intnet: "sandbox_net"


    kali.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "8"

      vb.name = "Kali"
    end

    kali.vm.provision "shell", path: "kali_install.sh"
  end


end
