name: Black python formatter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "./volatility3"
          # FIXME: Remove when Volatility3 minimum Python version is >3.8
          version: "24.8.0"
