name: build-pyinstaller
on:
  push:
    branches:
      - stable
      - develop
      - "release/**"
  pull_request:
    branches:
      - stable
      - "release/**"
  workflow_dispatch:

jobs:
  exe:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .[full,cloud]

      - name: Pyinstall executable
        run: |
          pyinstaller --clean -y vol.spec
          pyinstaller --clean -y volshell.spec

      - name: Move files
        run: |
          mv dist/vol.exe vol.exe
          mv dist/volshell.exe volshell.exe

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: volatility3-pyinstaller
          path: |
            vol.exe
            volshell.exe
            README.md
            LICENSE.txt
